# DEEP LEARNING
## TUẦN 3: NUMPY, PANDAS, MATPLOTLIB

Pandas là một thư viện tương đối mới, được xây dựng dựa trên NumPy, và cung cấp một cách cài đặt hiệu quả cho cấu trúc dữ liệu DataFrame.

DataFrame về bản chất là các mảng đa chiều (multidimensional arrays) có gắn nhãn hàng (row labels) và nhãn cột (column labels), đồng thời thường chứa dữ liệu không đồng nhất về kiểu (heterogeneous types) và/hoặc giá trị bị thiếu (missing data).

Bằng việc cung cấp một giao diện lưu trữ thuận tiện cho dữ liệu có nhãn (labeled data), Pandas triển khai nhiều phép toán xử lý dữ liệu mạnh mẽ, quen thuộc với người dùng các hệ quản trị cơ sở dữ liệu (database frameworks) cũng như các chương trình bảng tính (spreadsheet programs).

Mặc dù cấu trúc dữ liệu ndarray của NumPy cung cấp các tính năng nền tảng quan trọng, nhưng những hạn chế của nó trở nên rõ ràng khi cần sự linh hoạt cao hơn, chẳng hạn như gắn nhãn cho dữ liệu, xử lý dữ liệu bị thiếu, v.v.

Pandas cung cấp khả năng truy cập và xử lý hiệu quả các tác vụ “data munging” (tiền xử lý, làm sạch và biến đổi dữ liệu) — những công việc chiếm phần lớn thời gian làm việc.

In [1]:
import pandas as pd
pd.__version__

'2.2.3'

# Series
-----
Tạo Series từ list

In [2]:
data_pd = pd.Series([0.5,0.3,1.0,2.0])
data_pd

0    0.5
1    0.3
2    1.0
3    2.0
dtype: float64

Tạo Series từ Numpy array

In [4]:
import numpy as np
numpy_arr = np.arange(5)
data_pd = pd.Series(numpy_arr)
data_pd

0    0
1    1
2    2
3    3
4    4
dtype: int64

Attribute

In [5]:
data_pd.values

array([0, 1, 2, 3, 4])

In [6]:
data_pd.index

RangeIndex(start=0, stop=5, step=1)

Indexing

In [7]:
data_pd[1]

np.int64(1)

In [12]:
data_pd[-2:]

3    3
4    4
dtype: int64

In [14]:
data_pd[-1] #-> Không có chỉ số index là -1

KeyError: -1

Letter indexing

In [17]:
# Chỉ số nguyên khó dùng => thử đổi sang chữ cái
data_pd = pd.Series([1.25,2.0,0.75,1.0], index = ['a', 'b', 'c', 'd'])

In [24]:
data_pd[-1]

C:\Users\Admin\AppData\Local\Temp\ipykernel_18528\1254736883.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data_pd[-1]

np.float64(1.0)

In [19]:
data_pd['b']

np.float64(2.0)

# BTVN 1
Giải thích data_pd[-1]

Combined indexing

In [25]:
index = ['a', 'b', 'c', 'd', 3]
data_pd = pd.Series(numpy_arr, index = index)

In [26]:
data_pd['a']

np.int64(0)

In [27]:
data_pd[3]

np.int64(4)

pandas and dictionary

In [30]:
# Hệ thống chỉ mục của pandas có cấu trúc tương tự dictionary
# => Việc tạo một đối tượng pandas từ Dictionary là điều hoàn toàn dễ hiểu
some_population_dict = {'SaiGon': 59,
                        'Đồng Nai': 60,
                        'Bình Thuận': 86,
                        'Hà Nội': 29}
data_pd = pd.Series(some_population_dict)
data_pd['SaiGon']

np.int64(59)

In [31]:
# Pandas cũng hỗ trợ slising
# lưu ý: slising theo index label là "bao gồm có điểm kết thúc"
data_pd['SaiGon':'Hà Nội']

SaiGon        59
Đồng Nai      60
Bình Thuận    86
Hà Nội        29
dtype: int64

pandas and Scalar

In [32]:
# Dữ iệu có thể là một giá trị vô hướng (Scalar)
# và giá trị này sẽ được lập lại để điền vào toàn bộ index đã chỉ định
data_pd = pd.Series(5, index=[2,3,8])
data_pd

2    5
3    5
8    5
dtype: int64

Dataframe
DataFrame tương tự mảng 2 chiều, với index hàng và tên cột linh hoạt; về bản chất là tập hợp các Series được căn chỉnh theo index.

Tạo data frame với 2 dict

In [44]:
some_population_dict = {'SaiGon': 59,
                        'Đồng Nai':60,
                        'Bình Thuận': 86,
                        'Hà Nội': 29}
some_area_dict = {'SaiGon': 51,
                  'Đồng Nai': 600,
                  'Hà Nội': 33,
                  'Bình Thuận': 8686}
state = pd.DataFrame({"population": some_population_dict,
                      "area": some_area_dict})
state

            population  area
SaiGon              59    51
Đồng Nai            60   600
Bình Thuận          86  8686
Hà Nội              29    33

In [35]:
state['SaiGon':'Hà Nội']

            population   area
SaiGon            59.0   51.0
Đồng Nai          60.0  600.0
Bình Thuận        86.0    NaN
Hà Nội            29.0   33.0

In [36]:
state['SaiGon':'Hà Nội']['population']

SaiGon        59.0
Đồng Nai      60.0
Bình Thuận    86.0
Hà Nội        29.0
Name: population, dtype: float64

In [37]:
state['population']['SaiGon':'Hà Nội']

SaiGon        59.0
Đồng Nai      60.0
Bình Thuận    86.0
Hà Nội        29.0
Name: population, dtype: float64

In [38]:
state['population']['SaiGon':'Hà Nội']['area'] # cột area không tồn tại

KeyError: 'area'

In [45]:
state['area']

SaiGon          51
Đồng Nai       600
Bình Thuận    8686
Hà Nội          33
Name: area, dtype: int64

In [46]:
state.index

Index(['SaiGon', 'Đồng Nai', 'Bình Thuận', 'Hà Nội'], dtype='object')

In [47]:
state.index[-1]

'Hà Nội'

In [49]:
state.columns

Index(['population', 'area'], dtype='object')

In [48]:
state.columns[0:1]

Index(['population'], dtype='object')

Series indexing/slising/fancy indexing

In [50]:
import pandas as pd
data = pd.Series([0.75,0.5,1.0,2.0],
                 index = ['a', 'b', 'c', 'd'])
data

a    0.75
b    0.50
c    1.00
d    2.00
dtype: float64

explicit vs implicit index

In [51]:
data['b']

np.float64(0.5)

In [52]:
data[-1]

C:\Users\Admin\AppData\Local\Temp\ipykernel_18528\4056024912.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[-1]

np.float64(2.0)

In [53]:
data['a':'c']

a    0.75
b    0.50
c    1.00
dtype: float64

In [54]:
data[0:2]

a    0.75
b    0.50
dtype: float64

adding values

In [55]:
data['e'] = 10
data

a     0.75
b     0.50
c     1.00
d     2.00
e    10.00
dtype: float64

in

In [57]:
'a' in data

True

In [58]:
'f' in data

False

keys()

In [59]:
data.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

items()

In [60]:
list(data.items())

[('a', 0.75), ('b', 0.5), ('c', 1.0), ('d', 2.0), ('e', 10.0)]

values()

In [61]:
data.values

array([ 0.75,  0.5 ,  1.  ,  2.  , 10.  ])

masking

In [64]:
data[(data > 0.5) & (data < 10)]

a    0.75
c    1.00
d    2.00
dtype: float64

In [65]:
data[['a','e']]

a     0.75
e    10.00
dtype: float64